from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY_DIR = ROOT / 'registry' / 'repos'


def list_repo_configs() -> list[tuple[Path, dict[str, object]]]:
    entries: list[tuple[Path, dict[str, object]]] = []
    for path in sorted(REGISTRY_DIR.glob('*.json')):
        data = json.loads(path.read_text())
        if isinstance(data, dict) and isinstance(data.get('repo'), str):
            entries.append((path, data))
    return entries


def load_config(repo: str) -> tuple[Path, dict[str, object]]:
    for path, data in list_repo_configs():
        if data.get('repo') == repo:
            return path, data
    raise SystemExit(f'Repo config not found for {repo!r}')


def pick_workflow_preset(presets: list[str]) -> str | None:
    for name in ('site-ai', 'repo-docs', 'minimal'):
        if name in presets:
            return name
    return None


def render_workflow_yaml(workflow: dict[str, object]) -> str:
    with_block = workflow['with']
    lines = [
        'name: SET',
        '',
        'on:',
        '  workflow_dispatch:',
        '',
        'jobs:',
        '  set:',
        '    runs-on: ubuntu-latest',
        '    steps:',
        '      - uses: actions/checkout@v4',
        f"      - uses: {workflow['uses']}",
        '        with:',
    ]
    for key, value in with_block.items():
        lines.append(f'          {key}: "{value}"')
    return '\n'.join(lines) + '\n'


def repo_slug(repo: str) -> str:
    return repo.replace('/', '-')


def build_review_payload(repo: str, workflow: dict[str, object], unmapped: list[str]) -> dict[str, object]:
    apply_readiness = 'blocked' if unmapped else 'ready'
    blocked_by = list(unmapped)
    workflow_yaml = render_workflow_yaml(workflow)
    branch_name = f'codex/set-plan-{repo_slug(repo)}'
    title = f'chore(set): plan config apply for {repo}'
    body_lines = [
        f'# Planned SET workflow for `{repo}`',
        '',
        'This is a planning-only export generated from the central SET registry.',
        '',
        '## Proposed workflow target',
        f'- Path: `{workflow["path"]}`',
        f'- Uses: `{workflow["uses"]}`',
        '',
        '## Resolved inputs',
    ]
    for key, value in workflow['with'].items():
        body_lines.append(f'- `{key}`: `{value}`')
    if unmapped:
        body_lines.extend(['', '## Unmapped fields'])
        for item in unmapped:
            body_lines.append(f'- {item}')
    body_lines.extend([
        '',
        '## Notes',
        '- Generated by `python3 scripts/plan_config_apply.py`.',
        '- Planning only: no branch, no PR, no write to target repo.',
    ])
    body = '\n'.join(body_lines) + '\n'
    apply_simulation = {
        'repo': repo,
        'base_branch': 'main',
        'head_branch': branch_name,
        'target_files': [
            {
                'path': workflow['path'],
                'source_export': 'workflow.set.yml',
                'action': 'write',
            }
        ],
        'suggested_commit_message': title,
        'manual_steps': [
            f'git checkout -b {branch_name}',
            f'cp workflow.set.yml {workflow["path"]}',
            f'git add {workflow["path"]}',
            f'git commit -m "{title}"',
            f'gh pr create --repo {repo} --base main --head {branch_name} --title "{title}" --body-file pr-body.md',
        ],
    }
    return {
        'version': 1,
        'kind': 'set-pr-payload',
        'repo': repo,
        'apply_readiness': apply_readiness,
        'blocked_by': blocked_by,
        'next_action_label': 'Resolve unmapped fields' if unmapped else 'Review and apply planned workflow',
        'recommended_operator_step': unmapped[0] if unmapped else apply_simulation['manual_steps'][0],
        'next_shell_command': apply_simulation['manual_steps'][0],
        'target_branch': 'main',
        'head_branch': branch_name,
        'target_workflow_path': workflow['path'],
        'title': title,
        'suggested_commit_message': title,
        'body': body,
        'workflow_yaml': workflow_yaml,
        'gh_pr_create': {
            'repo': repo,
            'base': 'main',
            'head': branch_name,
            'title': title,
            'body_file': 'pr-body.md',
        },
        'apply_simulation': apply_simulation,
    }


def build_plan(config_path: Path, data: dict[str, object]) -> dict[str, object]:
    tools = data.get('tools', {}) if isinstance(data.get('tools'), dict) else {}
    agentsgen = tools.get('agentsgen', {}) if isinstance(tools.get('agentsgen'), dict) else {}
    presets = data.get('presets', []) if isinstance(data.get('presets'), list) else []
    workflow_preset = pick_workflow_preset([p for p in presets if isinstance(p, str)])

    with_block: dict[str, str] = {'agentsgen': 'true', 'autodetect': 'true', 'path': '.'}
    if workflow_preset:
        with_block['workflow_preset'] = workflow_preset

    for key in ('init', 'pack', 'check'):
        if key in agentsgen and isinstance(agentsgen[key], bool):
            with_block[key] = 'true' if agentsgen[key] else 'false'

    site = data.get('site') if isinstance(data.get('site'), dict) else {}
    site_url = site.get('url') if isinstance(site, dict) else None
    analyze_url = agentsgen.get('analyze_url')
    meta_url = agentsgen.get('meta_url')
    if isinstance(site_url, str) and site_url:
        with_block['site_url'] = site_url
        if workflow_preset == 'site-ai' or with_block.get('pack') == 'true':
            with_block['site_pack'] = 'true'
    if isinstance(analyze_url, str) and analyze_url:
        with_block['analyze'] = 'true'
        with_block['analyze_url'] = analyze_url
    if isinstance(meta_url, str) and meta_url:
        with_block['meta'] = 'true'
        with_block['meta_url'] = meta_url

    unmapped = []
    for key in ('repomap', 'snippets'):
        if agentsgen.get(key) is True:
            unmapped.append(f'agentsgen.{key} is in registry but not yet wired into SET action inputs')

    workflow = {
        'path': '.github/workflows/set.yml',
        'uses': 'markoblogo/SET@main',
        'with': with_block,
    }
    review_payload = build_review_payload(data['repo'], workflow, unmapped)
    return {
        'version': 1,
        'mode': 'planning-only',
        'repo': data['repo'],
        'source_config': str(config_path),
        'proposed_changes': [
            {
                'type': 'workflow',
                'workflow': workflow,
            }
        ],
        'review_payload': review_payload,
        'unmapped': unmapped,
        'notes': [
            'This planner does not open a PR or write files to the target repo.',
            'Use the output to review the intended SET workflow before any future apply step.',
        ],
    }




def derive_status_hint(plan: dict[str, object]) -> str:
    if plan.get('unmapped'):
        return 'needs-wiring'
    return 'ready-for-review'


def derive_priority_hint(plan: dict[str, object]) -> str:
    workflow = plan['proposed_changes'][0]['workflow']
    preset = workflow['with'].get('workflow_preset')
    if plan['repo'] == 'markoblogo/lab.abvx':
        return 'high'
    if plan.get('unmapped'):
        return 'medium'
    if preset == 'site-ai':
        return 'high'
    return 'normal'


def derive_apply_readiness(plan: dict[str, object]) -> str:
    if plan.get('unmapped'):
        return 'blocked'
    return 'ready'


def derive_blocked_by(plan: dict[str, object]) -> list[str]:
    return list(plan.get('unmapped', []))


def derive_next_action_label(plan: dict[str, object]) -> str:
    if plan.get('unmapped'):
        return 'Resolve unmapped fields'
    return 'Review and apply planned workflow'


def derive_recommended_operator_step(plan: dict[str, object]) -> str:
    if plan.get('unmapped'):
        return plan['unmapped'][0]
    return plan['review_payload']['apply_simulation']['manual_steps'][0]


def derive_next_shell_command(plan: dict[str, object]) -> str:
    return plan['review_payload']['apply_simulation']['manual_steps'][0]


def render_text(plan: dict[str, object]) -> str:
    workflow = plan['proposed_changes'][0]['workflow']
    with_block = workflow['with']
    gh_pr = plan['review_payload']['gh_pr_create']
    apply_sim = plan['review_payload']['apply_simulation']
    lines = [
        'SET config apply plan',
        f"repo: {plan['repo']}",
        f"source_config: {plan['source_config']}",
        f"target_workflow: {workflow['path']}",
        'with:',
    ]
    for key, value in with_block.items():
        lines.append(f'  {key}: {value}')
    unmapped = plan.get('unmapped', [])
    if unmapped:
        lines.append('unmapped:')
        for item in unmapped:
            lines.append(f'  - {item}')
        lines.append('blocked_by:')
        for item in derive_blocked_by(plan):
            lines.append(f'  - {item}')
    lines.extend([
        f"apply_readiness: {derive_apply_readiness(plan)}",
        f"next_action_label: {derive_next_action_label(plan)}",
        f"recommended_operator_step: {derive_recommended_operator_step(plan)}",
        f"next_shell_command: {derive_next_shell_command(plan)}",
        'review_bundle:',
        '  - plan.json',
        '  - workflow.set.yml',
        '  - pr-body.md',
        '  - gh-pr-create.json',
        '  - apply-simulation.json',
        'gh_pr_create:',
        f"  repo: {gh_pr['repo']}",
        f"  base: {gh_pr['base']}",
        f"  head: {gh_pr['head']}",
        f"  title: {gh_pr['title']}",
        f"  body_file: {gh_pr['body_file']}",
        'apply_simulation:',
        f"  base_branch: {apply_sim['base_branch']}",
        f"  head_branch: {apply_sim['head_branch']}",
        f"  target_file: {apply_sim['target_files'][0]['path']}",
        f"  commit_message: {apply_sim['suggested_commit_message']}",
        '  manual_steps:',
    ])
    for step in apply_sim['manual_steps']:
        lines.append(f'    - {step}')
    return '\n'.join(lines)


def render_batch_text(plans: list[dict[str, object]]) -> str:
    lines = ['SET config apply batch summary', f'repo_count: {len(plans)}']
    for plan in plans:
        status_hint = derive_status_hint(plan)
        priority_hint = derive_priority_hint(plan)
        workflow = plan['proposed_changes'][0]['workflow']
        gh_pr = plan['review_payload']['gh_pr_create']
        lines.extend([
            f'- {plan["repo"]}',
            f'  workflow_preset: {workflow["with"].get("workflow_preset", "none")}',
            f'  target_workflow: {workflow["path"]}',
            f'  head_branch: {gh_pr["head"]}',
            f'  title: {gh_pr["title"]}',
            f'  status_hint: {status_hint}',
            f'  priority_hint: {priority_hint}',
            f'  apply_readiness: {derive_apply_readiness(plan)}',
            f'  next_action_label: {derive_next_action_label(plan)}',
            f'  recommended_operator_step: {derive_recommended_operator_step(plan)}',
            f'  next_shell_command: {derive_next_shell_command(plan)}',
            f'  unmapped_count: {len(plan.get("unmapped", []))}',
        ])
    return '\n'.join(lines)


def export_plan(plan: dict[str, object], export_dir: Path) -> list[Path]:
    export_dir.mkdir(parents=True, exist_ok=True)
    review_payload = plan['review_payload']
    outputs = {
        'plan.json': json.dumps(plan, indent=2) + '\n',
        'workflow.set.yml': review_payload['workflow_yaml'],
        'pr-body.md': review_payload['body'],
        'gh-pr-create.json': json.dumps(review_payload['gh_pr_create'], indent=2) + '\n',
        'apply-simulation.json': json.dumps(review_payload['apply_simulation'], indent=2) + '\n',
    }
    written = []
    for name, content in outputs.items():
        path = export_dir / name
        path.write_text(content)
        written.append(path)
    return written


def export_batch(plans: list[dict[str, object]], export_dir: Path) -> list[Path]:
    export_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    summary = {
        'version': 1,
        'mode': 'planning-only-batch',
        'repo_count': len(plans),
        'repos': [
            {
                'repo': plan['repo'],
                'head_branch': plan['review_payload']['gh_pr_create']['head'],
                'target_workflow': plan['proposed_changes'][0]['workflow']['path'],
                'title': plan['review_payload']['gh_pr_create']['title'],
                'status_hint': derive_status_hint(plan),
                'priority_hint': derive_priority_hint(plan),
                'apply_readiness': derive_apply_readiness(plan),
                'blocked_by': derive_blocked_by(plan),
                'next_action_label': derive_next_action_label(plan),
                'recommended_operator_step': derive_recommended_operator_step(plan),
                'next_shell_command': derive_next_shell_command(plan),
                'unmapped_count': len(plan.get('unmapped', [])),
            }
            for plan in plans
        ],
    }
    batch_path = export_dir / 'batch-summary.json'
    batch_path.write_text(json.dumps(summary, indent=2) + '\n')
    written.append(batch_path)
    for plan in plans:
        repo_dir = export_dir / repo_slug(plan['repo'])
        written.extend(export_plan(plan, repo_dir))
    return written


def resolve_targets(repos: list[str], use_all: bool) -> list[tuple[Path, dict[str, object]]]:
    if use_all:
        return list_repo_configs()
    if not repos:
        raise SystemExit('Provide at least one repo or use --all')
    return [load_config(repo) for repo in repos]


def main() -> int:
    parser = argparse.ArgumentParser(description='Planning-only SET config apply helper.')
    parser.add_argument('repos', nargs='*', help='Repo name(s) in owner/name format')
    parser.add_argument('--all', action='store_true', help='Plan against every repo in registry/repos')
    parser.add_argument('--format', choices=('text', 'json'), default='text')
    parser.add_argument('--export-dir', help='Optional local directory for reviewable planner outputs.')
    args = parser.parse_args()

    targets = resolve_targets(args.repos, args.all)
    plans = [build_plan(config_path, data) for config_path, data in targets]
    multi = len(plans) > 1
    if args.export_dir:
        if multi:
            written = export_batch(plans, Path(args.export_dir))
            for plan in plans:
                repo_dir = Path(args.export_dir) / repo_slug(plan['repo'])
                plan['exported_files'] = [str(path) for path in sorted(repo_dir.iterdir())]
            batch_summary_path = Path(args.export_dir) / 'batch-summary.json'
        else:
            written = export_plan(plans[0], Path(args.export_dir))
            plans[0]['exported_files'] = [str(path) for path in written]
            batch_summary_path = None
    else:
        written = []
        batch_summary_path = None

    if args.format == 'json':
        if multi:
            payload = {'version': 1, 'mode': 'planning-only-batch', 'repo_count': len(plans), 'plans': plans}
            if batch_summary_path:
                payload['batch_summary_file'] = str(batch_summary_path)
            print(json.dumps(payload, indent=2))
        else:
            print(json.dumps(plans[0], indent=2))
    else:
        if multi:
            print(render_batch_text(plans))
            if args.export_dir:
                print('exported_files:')
                if batch_summary_path:
                    print(f'  - {batch_summary_path}')
                for plan in plans:
                    for path in plan.get('exported_files', []):
                        print(f'  - {path}')
        else:
            print(render_text(plans[0]))
            if args.export_dir:
                print('exported_files:')
                for path in plans[0]['exported_files']:
                    print(f'  - {path}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
